version: '3'
services:    
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tom
      MONGO_INITDB_ROOT_PASSWORD: StickyPot6


  express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tom
      ME_CONFIG_MONGODB_ADMINPASSWORD: StickyPot6